### ISSUE TITLE
Ownership and moving from p6c

### ISSUE THREAD

**Issue by 2colours** [dagurval/p6-Time-Duration#14]
Hi,

mostly asking @dagurval as the owner of the github repo and @masukomi as the de-facto author of the latest updates and zef publisher:
- is it intentional that masukomi published this distro to the "zef ecosystem"?
- if it is, does that mean that he's the de facto maintainer of this repo now? would it make sense to transfer ownership?
- in either case, if there is somebody to publish the releases on the "zef ecosystem", could this repo be removed from [p6c as well](https://github.com/Raku/ecosystem/blob/dd55bd4a9b841c41221198665f8f5cc63da439c0/META.list#L163)? The file name isn't even correct anymore and turning p6c off is long due.

**Comment by dagurval** [comment]
> if it is, does that mean that he's the de facto maintainer of this repo now? 

Yes

> would it make sense to transfer ownership?

IDK, what does that accomplish?

**Comment by 2colours** [comment]
Honestly, I don't really know either... from the technical point of view, perhaps the owner can distribute access rights, or for example archive or delete the repository. I think there's also the non-technical point of view that it seems a little confusing that the actual maintainer is not the owner (anymore). If you guys are okay with the situation, I suppose it can just work the way it is.

So, what about the p6c entry? If yall agree that it can be removed from there, it's really a PR with one line of modification, I could also just go ahead and do it.

**Comment by masukomi** [comment]
> is it intentional that masukomi published this distro to the "zef ecosystem"?

yeah, was one part because i'm the one going to be maintaining it now, one part because i don't think @dagurval  has a zef account.

> in either case, if there is somebody to publish the releases on the "zef ecosystem", could this repo be removed from [p6c as well](https://github.com/Raku/ecosystem/blob/dd55bd4a9b841c41221198665f8f5cc63da439c0/META.list#L163)? The file name isn't even correct anymore and turning p6c off is long due.

I'm happy do do that, but i don't know anything about that mechanism. Should I just make a PR to remove the line you pointed to @2colours ?

> would it make sense to transfer ownership?

Short term the value is that folks would be less inclined to poke @dagurval with comments / questions about it, which is probably a good thing since they're not interested in poking it these days (note: not meant as a negative in any way, I've got a few of those repos too). 

Long term, yeah now that you mention it we probably _should_ transfer the repo because then i could add other contributors (unlikely anyone would want to) or transfer ownership myself if years from now I wander away from raku and someone else wants to take up the torch. 

Honestly I've just been thinking in terms of "how do i get this up to date and installable in the new systems of raku" not really "what happens in 5 years"

**Comment by 2colours** [comment]
Yeah, that's also fair enough but if it's not too much to ask, with these advantages listed, it might make sense to pass it over in my opinion.

> Should I just make a PR to remove the line you pointed to @2colours ?

Yes, I think that's exactly how it works. One such a PR: https://github.com/Raku/ecosystem/pull/599/files. I think they are a rare sight simply because the main authors who removed their modules (already) actually have a commit bit; loads of commits like that in the recent times: https://github.com/Raku/ecosystem/commits/main

**Comment by 2colours** [comment]
FYI: the dist has been removed from p6c now.

**Comment by masukomi** [comment]
thanks @2colours 

closing this because i think it's been addressed. @dagurval and i can deal with transferring it later if he wants.
